theme: cayman
title: Yantram Blog
author: Sunny-Vats
email: ssunnyvvats.0608@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This blog page is for Java tutorial classes. I have tried to capture all the
  things in one place. To absorb all the knowledge, kindly practise as you read. 

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
